image: maven:latest

before_script:
  #  The following is to fix the delays in the JVM caused by the issue described here:
  #  https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html
  - mv /dev/random /dev/chaos
  - ln -s /dev/urandom /dev/random

  # This is to allow JavaFX tests to run in headless mode
  - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"

stages:
  - build
  - test
  - run

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn clean test

run:
  stage: run
  script:
    - mvn package
    - mvn exec:java