image: maven:latest

before_script:
  #  The following is to fix the delays in the JVM caused by the issue described here:
  #  https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html
  - mv /dev/random /dev/chaos
  - ln -s /dev/urandom /dev/random

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn clean verify
