image: maven:latest

before_script:
  - mv /dev/random /dev/chaos
  - ln -s /dev/urandom /dev/random

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn clean verify
