image: maven:latest

before_script:
  - apt-get install haveged
  - update-rc.d haveged defaults
  - service haveged start

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn clean verify
